name: Testing
on:
  - push
jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.6', '2.7']
    name: Rspec with Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: |
          bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
          bundle exec rspec
